# This is a basic workflow to help you get started with Actions

name: import:0.0

on:
#  push:
#    branches:
#      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : 
#    daily,every 5 hours #m h d/m m d/w 
    - cron:  '45 */12 * * *'
#    every 2 hour
#    - cron:  '30 */2 * * *'
#    every 3.rd of sept
#    - cron:  '* * 2 9 *' 
  
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/crecoding:2020.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: master
      - name: install aiohttp
        run: (pip3 install aiohttp)
      - name: install asyncio
        run: (pip3 install asyncio)
      - name: install CreGeoReference
        run: (pip3 install CreGeoReference)
      - name: install CreLanguageTranslate
        run: (pip3 install CreLanguageTranslate)
      - name: cd /cre/python/
        run: (cd /cre/python/)
      - name: cp mysecrets.py
        run: (cp mysecrets.orig.py mysecrets.py)
#      - name: init python
#        run: (/cre/init-python.sh)
      - name: Run import
        env:
            EXTREME_GH_TOKEN: ${{ secrets.EXTREME_GH_TOKEN }}
            EXTREME_LANGUAGE: ${{ secrets.EXTREME_LANGUAGE }}
            RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: (python3 import.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'terms.csv'
          tag_push: '--force'
